apiVersion: v2
name: book-store-chart
description: Helm Chart to deploy the Book Catalog API

type: application


version: 0.0.1 #Preference -> it ensure me that i am working in the very first version


appVersion: "1.16.0"
