apiVersion: v1
kind: Service
metadata:
  name: my-database-service
  namespace: postgres
spec:
  ports:
  - name: http
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: my-database
  type: ClusterIP