apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-database
  namespace: postgres
spec:
  serviceName: my-database-service
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: books
            - name: POSTGRES_USER
              value: books
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: database_password
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi